#!/usr/bin/env python3
"""
analysis/fit_arrhenius.py
Standalone Arrhenius fit: log(τ_grok) ~ a + b / T_eff_proxy.

Reads the master CSV produced by experiments/sweep_runner.py
(columns: lr, seed, tau_grok, T_eff_proxy) and fits a linear model
to log(τ) vs 1/T_eff_proxy.

Note: the authoritative paper figure uses B/lr as the temperature proxy
and is generated by final_output/analyser.py. This script is a
standalone alternative for quick re-fitting.

Usage:
    python analysis/fit_arrhenius.py
    python analysis/fit_arrhenius.py --master runs/arrhenius_transformer_master.csv --outdir runs
"""

import argparse
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats


def fit_and_plot(master_path, outdir):
    df = pd.read_csv(master_path)

    required = {'tau_grok', 'T_eff_proxy'}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"Master CSV is missing columns: {missing}. "
            "Expected format: lr, seed, tau_grok, T_eff_proxy "
            "(as produced by experiments/sweep_runner.py)."
        )

    valid = df[
        df['tau_grok'].notna() & (df['tau_grok'] > 0) &
        df['T_eff_proxy'].notna() & (df['T_eff_proxy'] > 0)
    ].copy()

    if len(valid) < 3:
        print(f"Not enough valid runs for fitting (got {len(valid)}, need ≥ 3).")
        return

    valid['log_tau'] = np.log(valid['tau_grok'])
    valid['inv_T']   = 1.0 / valid['T_eff_proxy']

    slope, intercept, r_value, p_value, std_err = stats.linregress(
        valid['inv_T'], valid['log_tau']
    )

    print("=" * 50)
    print("ARRHENIUS FIT RESULTS")
    print("=" * 50)
    print(f"log(τ) = {intercept:.4f} + {slope:.4f} × (1/T_eff)")
    print(f"R² = {r_value ** 2:.4f}")
    print(f"p-value = {p_value:.2e}")
    print(f"Standard error = {std_err:.4f}")

    # Plot.
    plt.figure(figsize=(6, 5))
    plt.scatter(valid['inv_T'], valid['log_tau'], alpha=0.6, label='Data')
    x_line = np.linspace(valid['inv_T'].min(), valid['inv_T'].max(), 100)
    plt.plot(x_line, intercept + slope * x_line, 'r-',
             label=f'fit: slope={slope:.3f}')
    plt.xlabel('1 / T_eff_proxy')
    plt.ylabel('log(τ_grok)')
    plt.title('Arrhenius scaling — modular addition (transformer)')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    out_path = os.path.join(outdir, 'arrhenius_fit.png')
    plt.savefig(out_path, dpi=150)
    plt.close()
    print(f"Plot saved to {out_path!r}.")

    # Text summary.
    summary_path = os.path.join(outdir, 'arrhenius_fit_summary.txt')
    with open(summary_path, 'w') as f:
        f.write(f"slope       = {slope:.6f}\n")
        f.write(f"intercept   = {intercept:.6f}\n")
        f.write(f"R_squared   = {r_value ** 2:.6f}\n")
        f.write(f"p_value     = {p_value:.6e}\n")
        f.write(f"std_err     = {std_err:.6f}\n")
    print(f"Summary saved to {summary_path!r}.")


def main():
    parser = argparse.ArgumentParser(
        description="Fit Arrhenius scaling from sweep_runner output."
    )
    parser.add_argument(
        "--master", type=str,
        default="runs/arrhenius_transformer_master.csv",
        help="Path to the master CSV from experiments/sweep_runner.py.",
    )
    parser.add_argument(
        "--outdir", type=str, default="runs",
        help="Directory for output figure and summary.",
    )
    args = parser.parse_args()
    os.makedirs(args.outdir, exist_ok=True)
    fit_and_plot(args.master, args.outdir)


if __name__ == "__main__":
    main()
